apiVersion: v1
kind: ServiceAccount
metadata:
 name: spark-sa

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
    name: role-manage
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "get", "watch", "list", "delete"]

---
 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: role-manage-rb
roleRef:
  kind: Role
  name: role-manage
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: spark-sa