apiVersion: "sparkoperator.k8s.io/v1beta2-1.1.2-2.4.5"
kind: ScheduledSparkApplication
metadata:
  name: spark-trends
spec:
  schedule: "@every 24h"
  concurrencyPolicy: Allow
  template:
    type: Python
    mode: cluster
    image: "registry.gitlab.com/arjit95/vidstream/spark-jobs:v1"
    imagePullPolicy: IfNotPresent
    mainApplicationFile: "local:///opt/src/trends.py"
    deps:
      jars:
        - local:///opt/src/jars/mysql.jar
        - local:///opt/src/jars/elasticsearch.jar
      pyFiles:
        - local:///opt/src/jars/mysql.jar
        - local:///opt/src/jars/elasticsearch.jar
    sparkVersion: "2.4.5"
    restartPolicy:
      type: Never
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      labels:
        version: 2.4.5
      serviceAccount: spark-sa
    executor:
      cores: 1
      instances: 1
      memory: "512m"
      labels:
        version: 2.4.5 
    envFrom:
    - secretRef:
      name: vidstream-secret
    - configMapRef:
      name: vidstream-config
    env:
      - name: INTERVAL
        value: "24h"