apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: vidstream-api
      context: src/api
    - image: hello-service
      context: src/hello
    - image: upload-service
      context: src/uploadservice
    - image: transcode-service
      context: src/transcodemaster
    - image: transcode-worker
      context: src/transcodeworker
    - image: transcode-reducer
      context: src/transcodereducer
    - image: stream-service
      context: src/streamservice
    - image: vidstream-web
      context: src/web
  tagPolicy:
    envTemplate:
        template: "{{.IMAGE_NAME}}:v1"
deploy:
  kubectl:
    manifests:
      - deploy/kubectl/configmap.yml
      - deploy/kubectl/hello.yml
      - deploy/kubectl/uploadservice.yml
      - deploy/kubectl/streamservice.yml
      - deploy/kubectl/transcodemaster.yml
      - deploy/kubectl/transcodeworker.yml
      - deploy/kubectl/transcodereducer.yml
      - deploy/kubectl/api.yml
      - deploy/kubectl/web.yml