apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: vidstream-api
      context: src/api
    - image: upload-service
      context: src/uploadservice
    - image: transcode-service
      context: src/transcodemaster
    - image: transcode-worker
      context: src/transcodeworker
    - image: transcode-reducer
      context: src/transcodereducer
    - image: stream-service
      context: src/streamservice
    - image: vidstream-web
      context: src/web
  tagPolicy:
    envTemplate:
        template: "{{.IMAGE_NAME}}:v1"
deploy:
  kubectl:
    manifests:
      - deploy/kubectl/pvc.yml
      - deploy/okteto/configmap.yml
      - deploy/okteto/uploadservice.yml
      - deploy/okteto/streamservice.yml
      - deploy/okteto/transcodemaster.yml
      - deploy/okteto/transcodeworker.yml
      - deploy/okteto/transcodereducer.yml
      - deploy/okteto/api.yml
      - deploy/okteto/web.yml