apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: vidstream-frontend
      context: src/frontend
    - image: hello-service
      context: src/hello
    - image: upload-service
      context: src/uploadservice
    - image: transcode-service
      context: src/transcodemaster
    - image: transcode-worker
      context: src/transcodeworker
    - image: transcode-reducer
      context: src/transcodereducer
  tagPolicy:
    envTemplate:
        template: "{{.IMAGE_NAME}}:v1"
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/configmap.yml
      - kubernetes-manifests/hello.yml
      - kubernetes-manifests/uploadservice.yml
      - kubernetes-manifests/transcodemaster.yml
      - kubernetes-manifests/transcodeworker.yml
      - kubernetes-manifests/transcodereducer.yml
      - kubernetes-manifests/frontend.yml