apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: docker.pkg.github.com/arjit95/vidstream/vidstream-api
      context: src
      docker:
        dockerfile: api/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/assets-service
      context: src
      docker:
        dockerfile: assetsservice/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/upload-service
      context: src
      docker: 
        dockerfile: uploadservice/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/transcode-service
      context: src
      docker: 
        dockerfile: transcodemaster/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/transcode-worker
      context: src
      docker: 
        dockerfile: transcodeworker/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/transcode-reducer
      context: src
      docker: 
        dockerfile: transcodereducer/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/metadata-service
      context: src
      docker: 
        dockerfile: metadata/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/recommendation-service
      context: src
      docker: 
        dockerfile: recommendation/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/auth-service
      context: src
      docker: 
        dockerfile: auth/Dockerfile
    - image: docker.pkg.github.com/arjit95/vidstream/fluentd-service
      context: src/fluentd
  local:
    push: false
  tagPolicy:
    envTemplate:
        template: "{{.IMAGE_NAME}}:v1"
deploy:
  kubectl:
    manifests:
      - deploy/kubectl/configmap.yml
      - deploy/kubectl/secrets.yml
      - deploy/kubectl/uploadservice.yml
      - deploy/kubectl/assetsservice.yml
      - deploy/kubectl/metadataservice.yml
      - deploy/kubectl/transcoder/master.yml
      - deploy/kubectl/transcoder/worker.yml
      - deploy/kubectl/transcoder/reducer.yml
      - deploy/kubectl/recommendationservice.yml
      - deploy/kubectl/api.yml
      - deploy/kubectl/auth.yml
      - deploy/kubectl/fluentd.yml