apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: registry.gitlab.com/arjit95/vidstream/vidstream-api
      context: src/api
    - image: registry.gitlab.com/arjit95/vidstream/stream-service
      context: src/streamservice
    - image: registry.gitlab.com/arjit95/vidstream/upload-service
      context: src
      docker: 
        dockerfile: uploadservice/Dockerfile
    - image: registry.gitlab.com/arjit95/vidstream/transcode-service
      context: src
      docker: 
        dockerfile: transcodemaster/Dockerfile
    - image: registry.gitlab.com/arjit95/vidstream/transcode-worker
      context: src
      docker: 
        dockerfile: transcodeworker/Dockerfile
    - image: registry.gitlab.com/arjit95/vidstream/transcode-reducer
      context: src
      docker: 
        dockerfile: transcodereducer/Dockerfile
    - image: registry.gitlab.com/arjit95/vidstream/metrics-service
      context: src
      docker: 
        dockerfile: metrics/Dockerfile
    - image: registry.gitlab.com/arjit95/vidstream/auth-service
      context: src
      docker: 
        dockerfile: auth/Dockerfile
    - image: registry.gitlab.com/arjit95/vidstream/vidstream-web
      context: src/web
  local:
    push: false
  tagPolicy:
    envTemplate:
        template: "{{.IMAGE_NAME}}:v1"
deploy:
  kubectl:
    manifests:
      - deploy/kubectl/configmap.yml
      - deploy/kubectl/secrets.yml
      - deploy/kubectl/elasticsearch.yml
      - deploy/kubectl/mongo.yml
      - deploy/kubectl/uploadservice.yml
      - deploy/kubectl/streamservice.yml
      - deploy/kubectl/transcoder/master.yml
      - deploy/kubectl/transcoder/worker.yml
      - deploy/kubectl/transcoder/reducer.yml
      - deploy/kubectl/metrics.yml
      - deploy/kubectl/api.yml
      - deploy/kubectl/auth.yml
      - deploy/kubectl/frontend.yml
