apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcode-worker
spec:
  selector:
    matchLabels:
      app: transcode-worker
  template:
    metadata:
      labels:
        app: transcode-worker
    spec:
      containers:
        - name: server
          image: registry.gitlab.com/arjit95/vidstream/transcode-worker:v1
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          envFrom:
          - configMapRef:
                name: vidstream-config
          - secretRef:
                name: vidstream-secret
          volumeMounts:
          - name: pv0001
            mountPath: /data
      volumes:
      - name: pv0001
        persistentVolumeClaim:
          claimName: upload-pvc
          readOnly: false
