query getUserChannels($username: String!, $pagination: PaginatedInput) {
  channels(username: $username, pagination: $pagination) {
    total
    result {
      id
      title
      subscribers
    }
  }
}
