query Comments($video_id: String!, $pagination: PaginatedInput, $parent_id: String) {
    getComments(video_id: $video_id, pagination: $pagination, parent_id: $parent_id) {
        result {
            id
            user {
                username
                name
            }
            created_at
            likes
            dislikes
            content
        }
        total
    }
}