query Comments($video_id: String!, $pagination: PaginatedInput, $parent: String) {
    getComments(video_id: $video_id, pagination: $pagination, parent: $parent) {
        result {
            id
            user {
                username
                name
            }
            created_at
            likes
            dislikes
            content
            liked
        }
        total
    }
}