query Videos($pagination: PaginatedInput) {
    recentVideos(pagination: $pagination) {
        total
        result {
        id
        title
        uploaded_at
        views
        channel {
            id
            title
        }
        }
    }
}