query getVideo($id: String!) {
  video(id: $id) {
    id
    title
    uploaded_at
    views
    channel {
      id
      title
      subscribers
    }
    user {
      username
    }
    likes
    dislikes
    description
    tags
    categories
    liked
  }
}
