query getVideos($username: String, $channel_id: String, $pagination: PaginatedInput ) {
  videos(username: $username, channel_id: $channel_id, pagination: $pagination) {
    total
    result {
      id
      title
      uploaded_at
      views
      channel {
        id
        title
      }
    }
  }
}
