apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service
spec:
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
        - name: server
          image: stream-service:v1
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          envFrom:
          - configMapRef:
                name: network-config
          - configMapRef:
                name: storage-config
          - configMapRef:
                name: queue-config
          env:
          - name: PORT
            value: "8080"
          volumeMounts:
          - name: pv0001
            mountPath: /data

      volumes:
      - name: pv0001
        persistentVolumeClaim:
          claimName: upload-pvc
          readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: stream-service
spec:
  type: ClusterIP
  selector:
    app: stream-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: tcp
    port: 9222
    targetPort: 9222