apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
  namespace: vidstream
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi