apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: nfs
  hostPath:
    path: /home/arjit/nfs
  persistentVolumeReclaimPolicy: Delete
