apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    kind: PersistentVolumeClaim
    name: upload-pvc
  storageClassName: nfs
  hostPath:
    path: /data/nfs
  persistentVolumeReclaimPolicy: Delete