apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-service
spec:
  selector:
    matchLabels:
      app: assets-service
  template:
    metadata:
      labels:
        app: assets-service
    spec:
      containers:
        - name: server
          image: registry.gitlab.com/arjit95/vidstream/assets-service:v1
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          envFrom:
          - configMapRef:
                name: network-config
          - configMapRef:
                name: storage-config
          - configMapRef:
                name: queue-config
          env:
          - name: PORT
            value: "8080"
          - name: QUEUE_USERNAME
            valueFrom:
              secretKeyRef:
                name: queue-secret
                key: username
          - name: QUEUE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: queue-secret
                key: password
          volumeMounts:
          - name: pv0001
            mountPath: /data

      volumes:
      - name: pv0001
        persistentVolumeClaim:
          claimName: upload-pvc
          readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: assets-service
spec:
  type: ClusterIP
  selector:
    app: assets-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080