apiVersion: v1

kind: ConfigMap
metadata:
    name: network-config
data:
    API_SERVICE_ADDR: http://api-service:8080
    UPLOAD_SERVICE_ADDR: http://upload-service:8080
    QUEUE_SERVICE: amqp://rabbitmq:5672
    STREAM_SERVICE_ADDR: http://stream-service:8080
    DB_SERVICE_ADDR: mongodb://mongodb:27017
    ELASTICSEARCH_ADDR: https://elasticsearch:9200
    LOGGER_SERVICE_ADDR: tcp://fluentd-service:24224
    AUTH_SERVICE_ADDR: http://auth-service:8080
    METRICS_SERVICE_ADDR: http://metrics-service:8080
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cors-config
data:
  CORS_ALLOWED_ORIGINS: '*'

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: storage-config
data:
    UPLOAD_DIR: /data/uploads
    CONVERTED_DIR: /data/converted
    DB_NAME: vidstream

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: queue-config
data:
    TRANSCODE_QUEUE: transcode_queue
    CONVERT_QUEUE: convert_queue
    REDUCE_QUEUE: reduce_queue
