apiVersion: v1

kind: ConfigMap
metadata:
    name: network-config
data:
    # JAEGER_SERVICE_ADDR: jaeger-query.istio-system:16686
    API_SERVICE_ADDR: http://api-service:8080
    UPLOAD_SERVICE_ADDR: http://upload-service:8080
    QUEUE_SERVICE: amqp://rabbitmq:5672
    STREAM_SERVICE_ADDR: http://stream-service:8080
    DB_SERVICE: mysql:3306
    ELASTICSEARCH_ADDR: elasticsearch-arjit95.cloud.okteto.net
    LOGGER_SERVICE_ADDR: tcp://fluentd-service:24224

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: storage-config
data:
    UPLOAD_DIR: /data/uploads
    CONVERTED_DIR: /data/converted

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: queue-config
data:
    TRANSCODE_QUEUE: transcode_queue
    CONVERT_QUEUE: convert_queue
    REDUCE_QUEUE: reduce_queue
