apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-service
spec:
  selector:
    matchLabels:
      app: fluentd-service
  template:
    metadata:
      labels:
        app: fluentd-service
    spec:
      containers:
        - name: server
          image: docker.pkg.github.com/arjit95/vidstream/fluentd-service:v1
          envFrom:
          - configMapRef:
              name: vidstream-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
spec:
  type: ClusterIP
  selector:
    app: fluentd-service
  ports:
  - name: tcp
    port: 24224
    targetPort: 24224
