apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-service
spec:
  selector:
    matchLabels:
      app: metrics-service
  template:
    metadata:
      labels:
        app: metrics-service
    spec:
      containers:
        - name: server
          image: registry.gitlab.com/arjit95/vidstream/metrics-service:v1
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          env:
            - name: PORT
              value: "8080"
          envFrom:
          - configMapRef:
              name: network-config
          - configMapRef:
              name: storage-config
          - secretRef:
              name: network-secret

---
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
spec:
  type: ClusterIP
  selector:
    app: metrics-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
