apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: server
          image: docker.pkg.github.com/arjit95/vidstream/recommendation-service:v1
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
          envFrom:
          - configMapRef:
              name: vidstream-config
          - secretRef:
              name: vidstream-secret

---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: tcp
    port: 9229
    targetPort: 9229