apiVersion: v1
kind: Secret
metadata:
  name: queue-secret
type: Opaque
data:
  username: dGVzdA== # test
  password: dGVzdA==

---
apiVersion: v1
kind: Secret
metadata:
  name: network-secret
type: Opaque
data:
  JWT_TOKEN_SECRET: dGVzdA==
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQ=